---
- name: Deploy web server on VM1 and VM2
  hosts: webservers
  become: yes
  tasks:
    - name: Install Apache web server
      ansible.builtin.yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"
    
    - name: Install Nginx web server
      ansible.builtin.apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Configure Apache to listen on port 8080
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        line: 'Listen 8080'
      when: ansible_os_family == "RedHat"
      notify: restart apache

    - name: Configure Nginx to listen on port 8080
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      when: ansible_os_family == "Debian"
      notify: restart nginx

    - name: Start and enable Apache web server
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Start and enable Nginx web server
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Deploy a simple HTML page
      ansible.builtin.copy:
        content: |
          {% if inventory_hostname == 'VM1' %}
          <h1>Hello World from SJSU-1</h1>
          {% else %}
          <h1>Hello World from SJSU-2</h1>
          {% endif %}
        dest: /var/www/html/index.html
      when: ansible_os_family == "RedHat"
    
    - name: Deploy a simple HTML page for Nginx
      ansible.builtin.copy:
        content: |
          {% if inventory_hostname == 'VM1' %}
          <h1>Hello World from SJSU-1</h1>
          {% else %}
          <h1>Hello World from SJSU-2</h1>
          {% endif %}
        dest: /var/www/html/index.html
      when: ansible_os_family == "Debian"

  handlers:
    - name: restart apache
      ansible.builtin.service:
        name: httpd
        state: restarted

    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

- name: Un-deploy web server on VM1 and VM2
  hosts: webservers
  become: yes
  tasks:
    - name: Stop and remove Apache web server
      ansible.builtin.service:
        name: httpd
        state: stopped
      when: ansible_os_family == "RedHat"

    - name: Stop and remove Nginx web server
      ansible.builtin.service:
        name: nginx
        state: stopped
      when: ansible_os_family == "Debian"

    - name: Remove Apache package
      ansible.builtin.yum:
        name: httpd
        state: absent
      when: ansible_os_family == "RedHat"

    - name: Remove Nginx package
      ansible.builtin.apt:
        name: nginx
        state: absent
      when: ansible_os_family == "Debian"

    - name: Remove web page
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent